import {
  Activity,
  Bot,
  BookOpenCheck,
  BriefcaseBusiness,
  Database,
  Download,
  ExternalLink,
  Github,
  Globe2,
  GraduationCap,
  HeartPulse,
  Linkedin,
  Mail,
  Network,
  ShieldCheck,
  Target,
  TestTube2,
  TrendingUp,
  UsersRound,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "../data/portfolio";

export const icons: Record<IconKey, LucideIcon> = {
  activity: Activity,
  ai: Bot,
  analytics: TrendingUp,
  automation: Workflow,
  book: BookOpenCheck,
  briefcase: BriefcaseBusiness,
  database: Database,
  download: Download,
  external: ExternalLink,
  github: Github,
  globe: Globe2,
  graduation: GraduationCap,
  heart: HeartPulse,
  linkedin: Linkedin,
  mail: Mail,
  network: Network,
  research: TestTube2,
  shield: ShieldCheck,
  target: Target,
  users: UsersRound,
};
